<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="V2IT01" ignored="0" name="Default test" tests="4" failures="1" timestamp="09 Apr 2019 13:29:19 GMT" time="344.818" errors="0">
  <testcase name="Company_Login_Testcase" time="9.621" classname="Driver_Started_Company_Module.Driver_Class"/>
  <testcase name="Manage_Assessment" time="103.162" classname="Driver_Started_Company_Module.Driver_Class"/>
  <testcase name="Manage_Book_Assessment" time="41.092" classname="Driver_Started_Company_Module.Driver_Class"/>
  <testcase name="Manage_Candidate_Testcases" time="185.057" classname="Driver_Started_Company_Module.Driver_Class">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="19">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 19
at Hiremee_Company_Module_Pages.Company_Pro_Manage_Candidate_Page.company_manage_candidate(Company_Pro_Manage_Candidate_Page.java:75)
at Hiremee_Company_Module_Testcases.Company_Pro_Manage_Candidate_Testcase.Manage_candidate_Test(Company_Pro_Manage_Candidate_Testcase.java:25)
at Driver_Started_Company_Module.Driver_Class.Manage_Candidate_Testcases(Driver_Class.java:268)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Manage_Candidate_Testcases -->
</testsuite> <!-- Default test -->
